studentblog/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class BlogPostForm(FlaskForm):    
    title = StringField('Title', validators=[DataRequired()])
    text = TextAreaField('Text', validators=[DataRequired()])
    submit = SubmitField('Blog Post')

studentblog/blog_posts/views.py
from flask import render_template,url_for,flash, redirect,request,Blueprint
from flask_login import current_user,login_required
from studentblog import db
from studentblog.models import BlogPost
from studentblog.blog_posts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts',__name__)

@blog_posts.route('/create',methods=['GET','POST'])
@login_required
def create_post():
    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post = BlogPost(title=form.title.data,
                             text=form.text.data,
                             user_id=current_user.id
                             )
        db.session.add(blog_post)
        db.session.commit()
        flash("Blog Post Created")
        return redirect(url_for('core.index'))

    return render_template('create_post.html',form=form)



@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    print(request.referrer)
    
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    blog_post.previous_url = request.referrer
    return render_template('blog_post.html',title=blog_post.title,
                            date=blog_post.date,post=blog_post
    )

@blog_posts.route("/<int:blog_post_id>/update", methods=['GET', 'POST'])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
       
        abort(403)

    form = BlogPostForm()
    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.text = form.text.data
        db.session.commit()
        flash('Post Updated')
        return redirect(url_for('blog_posts.blog_post', blog_post_id=blog_post.id))
   
    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text
    return render_template('create_post.html', title='Update',
                           form=form)


@blog_posts.route("/<int:blog_post_id>/delete", methods=['POST'])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)
    db.session.delete(blog_post)
    db.session.commit()
    flash('Post has been deleted')
    return redirect(url_for('core.index'))

studentblog/core/views.py
from flask import render_template,request,Blueprint
from studentblog.models import BlogPost

core = Blueprint('core',__name__)

@core.route('/')
def index():
    
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('index.html',blog_posts=blog_posts)

@core.route('/info')
def info():
  
    return render_template('info.html')

studentblog/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from studentblog import db
from werkzeug.security import generate_password_hash,check_password_hash
from studentblog.models import User, BlogPost
from studentblog.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from studentblog.users.picture_handler import add_profile_pic


users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering! Now you can login!')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():
       
        user = User.query.filter_by(email=form.email.data).first()     

        if user is not None and user.check_password(form.password.data):
          
            login_user(user)
            flash('Logged in successfully.')
            
            next = request.args.get('next')

           
            if next == None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)
    return render_template('login.html', form=form)




@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('core.index'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():

    form = UpdateUserForm()
    
    if form.validate_on_submit():
        print(form)
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)    
    return render_template('account.html', profile_image=profile_image, form=form)


@users.route("/<username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('user_blog_posts.html', blog_posts=blog_posts, user=user)

studentblog/templates/account.html
{% extends "base.html" %} {% block content %}

<style>
  
  .form-control:focus {
    box-shadow: none;
    border-color: #ba68c8;
  }
  .profile-button {
    background: rgb(99, 39, 120);
    box-shadow: none;
    border: none;
  }
  .profile-button:hover {
    background: #682773;
  }
  .profile-button:focus {
    background: #682773;
    box-shadow: none;
  }
  .profile-button:active {
    background: #682773;
    box-shadow: none;
  }
  .back:hover {
    color: #682773;
    cursor: pointer;
  }
  .labels {
    font-size: 11px;
  }
  .add-experience:hover {
    background: #ba68c8;
    color: #fff;
    cursor: pointer;
    border: solid 1px #ba68c8;
  }
</style>

<div class="container rounded bg-white mt-5 mb-5">
  <div class="row">
    <div class="col-md-12 border-right">
      <div class="p-3 py-5">
        <form  method="POST" action = "" enctype="multipart/form-data">
          {# This hidden_tag is a CSRF security feature. #} 
          {{ form.hidden_tag() }}

          <div class="jumbotron">
            <div align="center">
              <h1 class="text-info">Account Page - {{current_user.username}}</h1>
              <br>
              <img
                align="center"
                src="{{ url_for('static', filename='profile_pics/' + current_user.profile_image) }}"
              />
              <p>{{ current_user.email }}</p>
            </div>
          </div>

          <div class="form-group">
            {{ form.username(class='form-control', placeholder='User Name', required='required') }}
          </div>
          <div class="form-group">
            {{ form.email(class='form-control', placeholder='Email', required='required') }}
          </div>
          <div class="form-group">
            {{ form.picture.label(class="form-group") }}
            {{ form.picture(class="form-control-file") }}
          </div>
          <div class="mt-5 text-center">
            {{ form.submit(class="btn btn-primary profile-button") }}
          </div>

          <div class="form-group">
            {% if form.username.errors %}
                <ul class="errors">
                    {% for error in form.username.errors %}
                       <li class="text-danger">{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            {% if form.email.errors %}
                <ul class="errors">
                    {% for error in form.email.errors %}
                       <li class="text-danger">{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}           
        </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

studentblog/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    
    <link rel="stylesheet" type="text/css" href= "{{ url_for('static',filename='master.css') }}" >
    <title>SAU Students Blog - Where everybody meets !</title>
    
  </head>
  
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">
        <img src="{{ url_for('static', filename='profile_pics/logo.png') }}" width="75" height="75" alt="">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href="{{ url_for('core.index') }}">Home <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link" href="{{ url_for('core.info') }}">About Us</a>
          {% if current_user.is_authenticated %}
          <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Log Out</a>
          <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
          <a class="nav-item nav-link" href="{{ url_for('blog_posts.create_post') }}">Blog It!</a>
          {% else %}
          <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Log In</a>
          <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
          {% endif %}
        </div>
      </div>
    </nav>
    {% for message in get_flashed_messages() %}    

    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      {{message}}
    </div>

    {% endfor %}
    
    <div class="container">{% block content %} {% endblock %}</div>
  </body>
</html>

studentblog/templates/blog_post.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>{{ post.title }}</h1>
  <h2>Written by: {{post.author.username}}</h2>
  <h3>Published: {{ post.date.strftime('%B %d, %Y') }}</h3>
  <p>{{post.text}}</p>
   {% if post.author == current_user %}
     <div>
      <!-- <a class="btn btn-primary" href="{{ url_for('core.index') }}">Back</a> -->
       <a class="btn btn-primary" href="{{ post.previous_url }}">Back</a>
       <a class="btn btn-secondary" href="{{ url_for('blog_posts.update', blog_post_id=post.id) }}">Update</a>
       <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
     </div>     
   {% else %}
    <div>
      <!-- <a class="btn btn-primary" href="{{ url_for('core.index') }}">Back</a> -->
      <a class="btn btn-primary" href="{{ post.previous_url }}">Back</a>
    </div>
   {% endif %}
</div>




  <!-- Modal for Pop Up-->
  {# https://getbootstrap.com/docs/4.1/components/modal/ #}
  {# Notice how the link with the id to the button above! #}
  <div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Post Pop up Modal</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this blog post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

          <form action="{{ url_for('blog_posts.delete_post', blog_post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

studentblog/templates/create_post.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <form class="form-group" method="POST">
     {{ form.hidden_tag() }}

     <div class="form-group">
     {{ form.title.label(class="form-control-label blog-lable") }}
     {{ form.title(class="form-control form-control-lg ") }}
     </div>
     <div class="form-group">
     {{ form.text.label(class="form-control-label blog-lable") }}
     {{ form.text(class="form-control form-control-lg") }}
     </div>
     <div class="form-group">
         <!-- {{ form.submit(class="btn btn-outline-info") }} -->
         {{ form.submit(class="btn btn-info") }}
     </div>
  </form>

</div>

{% endblock content %}

studentblog/templates/index.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron alert alert-primary">
    <h1>SAU Student(s) Blog</h1>
    <p>Welcome to our own SAU's Blog Page !</p>
  </div>

  <div class="container">

    {# Go through each blog post #}
    {% for post in blog_posts.items %}

    <div class="card alert alert-dark" style="opacity: 0.9 ;" >

      <div class="card-body">


        <h3><a class="card-title" style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif ;" href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h3>
        <a style="color:crimson ;" href="{{ url_for('users.user_posts', username=post.author.username) }}">Written By: {{ post.author.username }}</a>
        <p>Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
        <hr>
        <p class="card-text">{{ post.text[:100] }}...</p>
        <a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}" class="btn btn-success">Read Blog Post</a>
      </div>
    </div>

   {% endfor %}

   <nav aria-label="Page navigation example">
     <ul class="pagination justify-content-center">
       {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if blog_posts.page == page_num %}
          <li class="page-item disabled">
            <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
          </li>
          {% else %}
            <li class="page-item"><a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
          {% endif %}
      {% endfor %}
    </nav>

{% endblock %}

studentblog/templates/info.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>Southern Arkansas University - Student Blog</h1>
  <p></p>  
</div>

{% endblock %}

studentblog/templates/login.html
{% extends "base.html" %}
{% block content %}
<style>
    .login-form {
        width: 340px;
        margin: 50px auto;
          font-size: 15px;
    }
    .login-form form {
        margin-bottom: 15px;
        background: #f7f7f7;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }
    .login-form h2 {
        margin: 0 0 15px;
    }
    .form-control, .btn {
        min-height: 38px;
        border-radius: 2px;
    }
    .btn {        
        font-size: 15px;
        font-weight: bold;
    }
    </style>

<!-- <form method="POST">
    {# This hidden_tag is a CSRF security feature. #}
    {{ form.hidden_tag() }}
    {{ form.email.label }} {{ form.email() }}
    {{ form.password.label }} {{ form.password() }}
    {{ form.submit() }}
</form> -->

<div class="login-form">
    <form method="POST">
        {# This hidden_tag is a CSRF security feature. #}
        {{ form.hidden_tag() }}

        <h2 class="text-center">Log in</h2>       
        <div class="form-group">
            <!-- <input type="text" class="form-control" placeholder="Username" required="required"> -->
            {{ form.email(class='form-control', type='email', placeholder='Email', required='required') }}
        </div>
        <div class="form-group">
            <!-- <input type="password" class="form-control" placeholder="Password" required="required"> -->
            {{ form.password(class='form-control', placeholder='Password', required='required') }}
        </div>
        <div class="form-group">
            <!-- <button type="submit" class="btn btn-primary btn-block">Log in</button> -->
            {{ form.submit(class='btn btn-primary btn-block') }}
        </div>
        <div class="clearfix">
            <label class="float-left form-check-label"><input type="checkbox"> Remember me</label>
            <a href="#" class="float-right">Forgot Password?</a>
        </div>
        <div class="form-group">           
            {% if form.email.errors %}
                <ul class="errors">
                    {% for error in form.email.errors %}
                       <li class="text-danger">{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            {% if form.password.errors %}
                <ul class="errors">
                    {% for error in form.password.errors %}
                       <li class="text-danger">{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </form>
    <p class="text-center" style="background-color: gainsboro ;"><a href="{{ url_for('users.register') }}">Create an Account</a></p>
</div>
{% endblock %}

studentblog/templates/register.html
{% extends "base.html" %}
{% block content %}

<style>
    /* body {
        color: #fff;
        background: #63738a;
        font-family: 'Roboto', sans-serif;
    } */
    .form-control {
        height: 40px;
        box-shadow: none;
        color: #969fa4;
    }
    .form-control:focus {
        border-color: #5cb85c;
    }
    .form-control, .btn {        
        border-radius: 3px;
    }
    .signup-form {
        width: 450px;
        margin: 0 auto;
        padding: 30px 0;
          font-size: 15px;
    }
    .signup-form h2 {
        color: #636363;
        margin: 0 0 15px;
        position: relative;
        text-align: center;
    }
    .signup-form h2:before, .signup-form h2:after {
        content: "";
        height: 2px;
        width: 30%;
        background: #d4d4d4;
        position: absolute;
        top: 50%;
        z-index: 2;
    }	
    .signup-form h2:before {
        left: 0;
    }
    .signup-form h2:after {
        right: 0;
    }
    .signup-form .hint-text {
        color: #999;
        margin-bottom: 30px;
        text-align: center;
    }
    .signup-form form {
        color: #999;
        border-radius: 3px;
        margin-bottom: 15px;
        background: #f2f3f7;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }
    .signup-form .form-group {
        margin-bottom: 20px;
    }
    .signup-form input[type="checkbox"] {
        margin-top: 3px;
    }
    .signup-form .btn {        
        font-size: 16px;
        font-weight: bold;		
        min-width: 140px;
        outline: none !important;
    }
    .signup-form .row div:first-child {
        padding-right: 10px;
    }
    .signup-form .row div:last-child {
        padding-left: 10px;
    }    	
    .signup-form a {
        color: #fff;
        text-decoration: underline;
    }
    .signup-form a:hover {
        text-decoration: none;
    }
    .signup-form form a {
        color: #5cb85c;
        text-decoration: none;
    }	
    .signup-form form a:hover {
        text-decoration: underline;
    }  
    </style>

<div class="signup-form">
    <form method="post">
        {# This hidden_tag is a CSRF security feature. #}
        {{ form.csrf_token }}

		<h2>Register</h2>
		<p class="hint-text">Create your account. It's free and only takes a minute.</p>
        
        <div class="form-group">
            {{ form.username(class='form-control', placeholder='User Name', required='required') }}
        </div>
        <div class="form-group">
            {{ form.email(class='form-control', type='email', placeholder='Email', required='required') }}
        </div>
		<div class="form-group">
        
            {{ form.password(class='form-control', placeholder='Password', required='required') }}
        </div>
		<div class="form-group">
        
            {{ form.pass_confirm(class='form-control', placeholder='Confirm Password', required='required') }}
        </div>        
        <div class="form-group">
			<label class="form-check-label"><input type="checkbox" required="required"> I accept the <a href="#">Terms of Use</a> &amp; <a href="#">Privacy Policy</a></label>
		</div>
		<div class="form-group">
        
            {{ form.submit(class="btn btn-success btn-lg btn-block") }}
        </div>

        <div class="form-group">
            {% if form.username.errors %}
                <ul class="errors">
                    {% for error in form.username.errors %}
                       <li class="text-danger">{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            {% if form.email.errors %}
                <ul class="errors">
                    {% for error in form.email.errors %}
                       <li class="text-danger">{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            {% if form.password.errors %}
                <ul class="errors">
                    {% for error in form.password.errors %}
                       <li class="text-danger">{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </form>
	<div class="text-center">Already have an account? <a href="{{ url_for('users.login') }}">Sign in</a></div>
</div>

{% endblock content %}

studentblog/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <div align='center'>
      <h1>Welcome to the page for {{user.username}}</h1>
      <img align='center' src="{{ url_for('static', filename='profile_pics/' + user.profile_image) }}">
    </div>
  </div>



  {% for post in blog_posts.items %}
  <div style="background-color:gainsboro; margin-bottom:10px; padding: 10px ; opacity: 0.9;">
    <h2><a class="btn btn-info" href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
    Written by: <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username
      }}</a>
    <p class="text-muted">Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
    <br>
    <p>{{post.text}}</p>
    <br>
  </div>
  
  {% endfor %}



</div>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {# http://flask.pocoo.org/snippets/44/ #}

    {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if blog_posts.page == page_num %}
    <li class="page-item disabled">
      <a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num
        }}</a>
    </li>
    </li>
    {% else %}
    <li class="page-item"><a class="page-link"
        href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
    {% endif %}
    {% endfor %}
</nav>
{% endblock content %}